const GET_PROBLEM = 'GET_PROBLEM'
const ADD_PROBLEM = 'ADD_PROBLEM'
const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
const UPDATE_PROBLEMS = 'UPDATE_PROBLEMS'
const GET_PROBLEMS = 'GET_PROBLEMS'
const DELETE_PROBLEM = 'DELETE_PROBLEM'
const INITIALIZE_PROBLEMS = 'INITIALIZE_PROBLEMS'
const PROBLEM_LOADING = 'PROBLEM_LOADING'

const GET_TESTS = 'GET_TESTS'
const DELETE_TEST = 'DELETE_TEST'
const TEST_LOADING = 'TEST_LOADING'
const GET_INDEX = 'GET_INDEX'
const GET_CATEGORY = 'GET_CATEGORY'

const ADD_ANSWER = 'ADD_ANSWER'
const UPDATE_ANSWER = 'UPDATE_ANSWER'
const CLEAR_ANSWER = 'CLEAR_ANSWER'

export {
  GET_PROBLEM,
  ADD_PROBLEM,
  UPDATE_PROBLEM,
  UPDATE_PROBLEMS,
  DELETE_PROBLEM,
  GET_PROBLEMS,
  INITIALIZE_PROBLEMS,
  PROBLEM_LOADING,

  GET_TESTS,
  DELETE_TEST,
  GET_INDEX,
  TEST_LOADING,
  GET_CATEGORY,

  ADD_ANSWER,
  UPDATE_ANSWER,
  CLEAR_ANSWER,
}